### ISSUE TITLE
ios打包报错

### ISSUE THREAD

**Issue by druphliu** [chenwei116057/chenwei-plugin-amap#1]
Showing Recent Messages
Undefined symbol: _CNCopySupportedInterfaces

Undefined symbol: _CNCopyCurrentNetworkInfo

Undefined symbol: _SCNetworkReachabilitySetDispatchQueue

Undefined symbol: _SCNetworkReachabilitySetCallback

Undefined symbol: _SCError

Undefined symbol: _SCNetworkReachabilityGetFlags

Undefined symbol: _SCErrorString

Undefined symbol: _SCNetworkReachabilityCreateWithAddress

**Comment by chenwei116057** [comment]
Can you show me the specific steps when you pack and the screenshots of the contents under the build phase? According to your error message, this is not a plugin error

**Comment by site-chenwei** [comment]
> Showing Recent Messages
> Undefined symbol: _CNCopySupportedInterfaces
> 
> Undefined symbol: _CNCopyCurrentNetworkInfo
> 
> Undefined symbol: _SCNetworkReachabilitySetDispatchQueue
> 
> Undefined symbol: _SCNetworkReachabilitySetCallback
> 
> Undefined symbol: _SCError
> 
> Undefined symbol: _SCNetworkReachabilityGetFlags
> 
> Undefined symbol: _SCErrorString
> 
> Undefined symbol: _SCNetworkReachabilityCreateWithAddress

你能把你打包时的具体步骤及build phase下的内容截图给我看一下吗？根据你的错误信息，这个并不是插件错误

**Comment by druphliu** [comment]
正常步骤打包 然后正常流程build 没加任何额外东西 提示报这个错 找了个会ios的帮忙看 说是系统包没加载 手动加载了还是无效 ps ios13.0

**Comment by site-chenwei** [comment]
![image](https://user-images.githubusercontent.com/23025255/65656042-f7265200-e050-11e9-8398-6040220dc3aa.png)
打包模式一定要用Xcode的Legacy Build System,然后可以移除并重新添加libc++.tbd这个依赖，然后重新打包

**Comment by site-chenwei** [comment]
没有回复，暂时关闭，若还需帮助，可再次打开
