### ISSUE TITLE
ios调用无效

### ISSUE THREAD

**Issue by qq690712575** [chenwei116057/chenwei-plugin-amap#2]
AMapPlugin.getLocation(res => {
                        console.log(res)
                        console.log('res')
                    }, err => {
                        console.log('err')
                        console.log(err)
                    })
安卓调用可以，ios调用没有任何效果，既不成功 也不err
cordova9.0

**Comment by chenwei116057** [comment]
可以把调用的代码给我看一下吗？

**Comment by chenwei116057** [comment]
问题已解决，解决代码已合并，将于1.0.20版本中发布
