### ISSUE TITLE
android 打包报错

### ISSUE THREAD

**Issue by super-maoMao** [chenwei116057/chenwei-plugin-amap#4]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/28719409/211967570-df1d3d60-d99a-4d1c-a12c-e1f93859a8ae.png">

打包的时候，报 (请使用 -source 7 或更高版本以启用 diamond 运算符) 错误，无法打包

**Comment by site-chenwei** [comment]
这个是和你安卓启用的JDK版本有关系吧？

**Comment by super-maoMao** [comment]
> 这个是和你安卓启用的JDK版本有关系吧？

项目的 cordova-android = 6.3.0 不能升级，因为安卓文件夹修改了太多东西
JDK 就用的1.8版本

是因为算法不兼容吗，感觉像是不支持哇，因为不知道该如何修改，想请教一下

**Comment by site-chenwei** [comment]
你改下我插件的源码，把1.7以上的部分代码向下兼容一下就行，改动量很少，我再安卓里面用了泛型<>,把他删掉就行

**Comment by site-chenwei** [comment]
如果不太知道怎么改可以再联系我

**Comment by super-maoMao** [comment]
> 如果不太知道怎么改可以再联系我

抱歉我可能需要你的帮助，我对 android  真的是很不熟悉，研究了几天，但是真的是无从下手，可以告诉我修改哪些文件，怎么修改吗？

**Comment by site-chenwei** [comment]
@super-maoMao 删除src/main/andriod目录下所有文件里的<>就行
![image](https://user-images.githubusercontent.com/23025255/225038197-80d01123-0760-4a6c-96e2-fe7f6ee71e32.png)

**Comment by site-chenwei** [comment]
其实就是JDK1.6里面还不支持这些写法，JDK1.7之后才支持的

**Comment by super-maoMao** [comment]
> 其实就是JDK1.6里面还不支持这些写法，JDK1.7之后才支持的

好的，我近期尝试修改一下，十分的感谢！
